apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web-application
  template:
    metadata:
      labels:
        app: web-application
    spec:
      containers:
      - name: web-application-container
        image: # Название образа
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "128Mi"
            cpu: "1"
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]  # Команда для задержки старта контейнера, чтобы он успел инициализироваться
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - web-application
              topologyKey: "kubernetes.io/hostname"  # Используем hostname для распределения подов по нодам
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-application-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-application
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu # Указываем метрику CPU для скейлинга
      target:
        type: Utilization
        averageUtilization: 50 # Целевое использование CPU в процентах (50%)